# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jul  1 22:18:15 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(516, 418)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("applymovement-generator2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Ruby = QtGui.QWidget()
        self.Ruby.setObjectName(_fromUtf8("Ruby"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Ruby)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textRuby = QtGui.QTextBrowser(self.Ruby)
        self.textRuby.setObjectName(_fromUtf8("textRuby"))
        self.verticalLayout_2.addWidget(self.textRuby)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.bAlertRuby = QtGui.QPushButton(self.Ruby)
        self.bAlertRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bAlertRuby.setObjectName(_fromUtf8("bAlertRuby"))
        self.horizontalLayout_3.addWidget(self.bAlertRuby)
        self.bQRuby = QtGui.QPushButton(self.Ruby)
        self.bQRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bQRuby.setObjectName(_fromUtf8("bQRuby"))
        self.horizontalLayout_3.addWidget(self.bQRuby)
        self.bLoveRuby = QtGui.QPushButton(self.Ruby)
        self.bLoveRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bLoveRuby.setObjectName(_fromUtf8("bLoveRuby"))
        self.horizontalLayout_3.addWidget(self.bLoveRuby)
        self.bEndRuby = QtGui.QPushButton(self.Ruby)
        self.bEndRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bEndRuby.setObjectName(_fromUtf8("bEndRuby"))
        self.horizontalLayout_3.addWidget(self.bEndRuby)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Botomirar = QtGui.QRadioButton(self.Ruby)
        self.Botomirar.setChecked(True)
        self.Botomirar.setObjectName(_fromUtf8("Botomirar"))
        self.gridLayout_2.addWidget(self.Botomirar, 0, 0, 1, 1)
        self.Botoslow = QtGui.QRadioButton(self.Ruby)
        self.Botoslow.setObjectName(_fromUtf8("Botoslow"))
        self.gridLayout_2.addWidget(self.Botoslow, 1, 0, 1, 1)
        self.Botowalk = QtGui.QRadioButton(self.Ruby)
        self.Botowalk.setObjectName(_fromUtf8("Botowalk"))
        self.gridLayout_2.addWidget(self.Botowalk, 2, 0, 1, 1)
        self.Botorun = QtGui.QRadioButton(self.Ruby)
        self.Botorun.setObjectName(_fromUtf8("Botorun"))
        self.gridLayout_2.addWidget(self.Botorun, 3, 0, 1, 1)
        self.Botojump = QtGui.QRadioButton(self.Ruby)
        self.Botojump.setObjectName(_fromUtf8("Botojump"))
        self.gridLayout_2.addWidget(self.Botojump, 4, 0, 1, 1)
        self.bSt1Ruby = QtGui.QRadioButton(self.Ruby)
        self.bSt1Ruby.setObjectName(_fromUtf8("bSt1Ruby"))
        self.gridLayout_2.addWidget(self.bSt1Ruby, 0, 1, 1, 1)
        self.bSt3Ruby = QtGui.QRadioButton(self.Ruby)
        self.bSt3Ruby.setObjectName(_fromUtf8("bSt3Ruby"))
        self.gridLayout_2.addWidget(self.bSt3Ruby, 2, 1, 1, 1)
        self.bSt4Ruby = QtGui.QRadioButton(self.Ruby)
        self.bSt4Ruby.setObjectName(_fromUtf8("bSt4Ruby"))
        self.gridLayout_2.addWidget(self.bSt4Ruby, 3, 1, 1, 1)
        self.bSt2Ruby = QtGui.QRadioButton(self.Ruby)
        self.bSt2Ruby.setObjectName(_fromUtf8("bSt2Ruby"))
        self.gridLayout_2.addWidget(self.bSt2Ruby, 1, 1, 1, 1)
        self.bHideRuby = QtGui.QCheckBox(self.Ruby)
        self.bHideRuby.setObjectName(_fromUtf8("bHideRuby"))
        self.gridLayout_2.addWidget(self.bHideRuby, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.BotoUp = QtGui.QPushButton(self.Ruby)
        self.BotoUp.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoUp.setObjectName(_fromUtf8("BotoUp"))
        self.gridLayout.addWidget(self.BotoUp, 0, 1, 1, 1)
        self.BotoLeft = QtGui.QPushButton(self.Ruby)
        self.BotoLeft.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoLeft.setObjectName(_fromUtf8("BotoLeft"))
        self.gridLayout.addWidget(self.BotoLeft, 1, 0, 1, 1)
        self.BotoRight = QtGui.QPushButton(self.Ruby)
        self.BotoRight.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoRight.setObjectName(_fromUtf8("BotoRight"))
        self.gridLayout.addWidget(self.BotoRight, 1, 2, 1, 1)
        self.BotoDown = QtGui.QPushButton(self.Ruby)
        self.BotoDown.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoDown.setObjectName(_fromUtf8("BotoDown"))
        self.gridLayout.addWidget(self.BotoDown, 2, 1, 1, 1)
        self.ClearRuby = QtGui.QPushButton(self.Ruby)
        self.ClearRuby.setMaximumSize(QtCore.QSize(52, 16777215))
        self.ClearRuby.setObjectName(_fromUtf8("ClearRuby"))
        self.gridLayout.addWidget(self.ClearRuby, 1, 1, 1, 1)
        self.backspaceRuby = QtGui.QPushButton(self.Ruby)
        self.backspaceRuby.setMaximumSize(QtCore.QSize(52, 16777215))
        self.backspaceRuby.setObjectName(_fromUtf8("backspaceRuby"))
        self.gridLayout.addWidget(self.backspaceRuby, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.Ruby, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.TextFR = QtGui.QVBoxLayout()
        self.TextFR.setObjectName(_fromUtf8("TextFR"))
        self.textFR = QtGui.QTextBrowser(self.tab)
        self.textFR.setObjectName(_fromUtf8("textFR"))
        self.TextFR.addWidget(self.textFR)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.bAlertFR = QtGui.QPushButton(self.tab)
        self.bAlertFR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bAlertFR.setObjectName(_fromUtf8("bAlertFR"))
        self.horizontalLayout_6.addWidget(self.bAlertFR)
        self.bAlert2FR = QtGui.QPushButton(self.tab)
        self.bAlert2FR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bAlert2FR.setObjectName(_fromUtf8("bAlert2FR"))
        self.horizontalLayout_6.addWidget(self.bAlert2FR)
        self.bQFR = QtGui.QPushButton(self.tab)
        self.bQFR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bQFR.setObjectName(_fromUtf8("bQFR"))
        self.horizontalLayout_6.addWidget(self.bQFR)
        self.bXFR = QtGui.QPushButton(self.tab)
        self.bXFR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bXFR.setObjectName(_fromUtf8("bXFR"))
        self.horizontalLayout_6.addWidget(self.bXFR)
        self.bHappyFR = QtGui.QPushButton(self.tab)
        self.bHappyFR.setMaximumSize(QtCore.QSize(40, 16777215))
        self.bHappyFR.setObjectName(_fromUtf8("bHappyFR"))
        self.horizontalLayout_6.addWidget(self.bHappyFR)
        self.bEndFR = QtGui.QPushButton(self.tab)
        self.bEndFR.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bEndFR.setObjectName(_fromUtf8("bEndFR"))
        self.horizontalLayout_6.addWidget(self.bEndFR)
        self.TextFR.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.TextFR)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.bSt1FR = QtGui.QRadioButton(self.tab)
        self.bSt1FR.setObjectName(_fromUtf8("bSt1FR"))
        self.gridLayout_3.addWidget(self.bSt1FR, 1, 1, 1, 1)
        self.bSt2FR = QtGui.QRadioButton(self.tab)
        self.bSt2FR.setObjectName(_fromUtf8("bSt2FR"))
        self.gridLayout_3.addWidget(self.bSt2FR, 2, 1, 1, 1)
        self.bSt3FR = QtGui.QRadioButton(self.tab)
        self.bSt3FR.setObjectName(_fromUtf8("bSt3FR"))
        self.gridLayout_3.addWidget(self.bSt3FR, 3, 1, 1, 1)
        self.BotojumpFR = QtGui.QRadioButton(self.tab)
        self.BotojumpFR.setObjectName(_fromUtf8("BotojumpFR"))
        self.gridLayout_3.addWidget(self.BotojumpFR, 0, 1, 1, 1)
        self.BotomirarFR = QtGui.QRadioButton(self.tab)
        self.BotomirarFR.setChecked(True)
        self.BotomirarFR.setObjectName(_fromUtf8("BotomirarFR"))
        self.gridLayout_3.addWidget(self.BotomirarFR, 0, 0, 1, 1)
        self.BotoxslowFR = QtGui.QRadioButton(self.tab)
        self.BotoxslowFR.setObjectName(_fromUtf8("BotoxslowFR"))
        self.gridLayout_3.addWidget(self.BotoxslowFR, 1, 0, 1, 1)
        self.BotoslowFR = QtGui.QRadioButton(self.tab)
        self.BotoslowFR.setObjectName(_fromUtf8("BotoslowFR"))
        self.gridLayout_3.addWidget(self.BotoslowFR, 2, 0, 1, 1)
        self.BotowalkFR = QtGui.QRadioButton(self.tab)
        self.BotowalkFR.setObjectName(_fromUtf8("BotowalkFR"))
        self.gridLayout_3.addWidget(self.BotowalkFR, 3, 0, 1, 1)
        self.BotorunFR = QtGui.QRadioButton(self.tab)
        self.BotorunFR.setObjectName(_fromUtf8("BotorunFR"))
        self.gridLayout_3.addWidget(self.BotorunFR, 4, 0, 1, 1)
        self.bHideFR = QtGui.QCheckBox(self.tab)
        self.bHideFR.setObjectName(_fromUtf8("bHideFR"))
        self.gridLayout_3.addWidget(self.bHideFR, 4, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.BotoUpFR = QtGui.QPushButton(self.tab)
        self.BotoUpFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoUpFR.setObjectName(_fromUtf8("BotoUpFR"))
        self.gridLayout_6.addWidget(self.BotoUpFR, 0, 1, 1, 1)
        self.BotoLeftFR = QtGui.QPushButton(self.tab)
        self.BotoLeftFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoLeftFR.setObjectName(_fromUtf8("BotoLeftFR"))
        self.gridLayout_6.addWidget(self.BotoLeftFR, 1, 0, 1, 1)
        self.BotoRightFR = QtGui.QPushButton(self.tab)
        self.BotoRightFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoRightFR.setObjectName(_fromUtf8("BotoRightFR"))
        self.gridLayout_6.addWidget(self.BotoRightFR, 1, 2, 1, 1)
        self.BotoDownFR = QtGui.QPushButton(self.tab)
        self.BotoDownFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoDownFR.setObjectName(_fromUtf8("BotoDownFR"))
        self.gridLayout_6.addWidget(self.BotoDownFR, 2, 1, 1, 1)
        self.backspaceFR = QtGui.QPushButton(self.tab)
        self.backspaceFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.backspaceFR.setObjectName(_fromUtf8("backspaceFR"))
        self.gridLayout_6.addWidget(self.backspaceFR, 0, 0, 1, 1)
        self.ClearFR = QtGui.QPushButton(self.tab)
        self.ClearFR.setMaximumSize(QtCore.QSize(52, 16777215))
        self.ClearFR.setObjectName(_fromUtf8("ClearFR"))
        self.gridLayout_6.addWidget(self.ClearFR, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionFRList = QtGui.QAction(MainWindow)
        self.actionFRList.setObjectName(_fromUtf8("actionFRList"))
        self.actionRubyList = QtGui.QAction(MainWindow)
        self.actionRubyList.setObjectName(_fromUtf8("actionRubyList"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionRubyList)
        self.menuTools.addAction(self.actionFRList)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "applymovement-gen", None, QtGui.QApplication.UnicodeUTF8))
        self.textRuby.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\'---------</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bAlertRuby.setText(QtGui.QApplication.translate("MainWindow", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.bQRuby.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.bLoveRuby.setText(QtGui.QApplication.translate("MainWindow", "<3", None, QtGui.QApplication.UnicodeUTF8))
        self.bEndRuby.setText(QtGui.QApplication.translate("MainWindow", "END", None, QtGui.QApplication.UnicodeUTF8))
        self.Botomirar.setText(QtGui.QApplication.translate("MainWindow", "Face", None, QtGui.QApplication.UnicodeUTF8))
        self.Botoslow.setText(QtGui.QApplication.translate("MainWindow", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.Botowalk.setText(QtGui.QApplication.translate("MainWindow", "Walk", None, QtGui.QApplication.UnicodeUTF8))
        self.Botorun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.Botojump.setText(QtGui.QApplication.translate("MainWindow", "Jump", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt1Ruby.setText(QtGui.QApplication.translate("MainWindow", "St1", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt3Ruby.setText(QtGui.QApplication.translate("MainWindow", "St3", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt4Ruby.setText(QtGui.QApplication.translate("MainWindow", "St4", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt2Ruby.setText(QtGui.QApplication.translate("MainWindow", "St2", None, QtGui.QApplication.UnicodeUTF8))
        self.bHideRuby.setText(QtGui.QApplication.translate("MainWindow", "Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoUp.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoLeft.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoRight.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoDown.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearRuby.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.backspaceRuby.setText(QtGui.QApplication.translate("MainWindow", "←", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ruby), QtGui.QApplication.translate("MainWindow", "R/S/E", None, QtGui.QApplication.UnicodeUTF8))
        self.textFR.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\'---------</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.bAlertFR.setText(QtGui.QApplication.translate("MainWindow", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.bAlert2FR.setText(QtGui.QApplication.translate("MainWindow", "!!", None, QtGui.QApplication.UnicodeUTF8))
        self.bQFR.setText(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.bXFR.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.bHappyFR.setText(QtGui.QApplication.translate("MainWindow", "^^", None, QtGui.QApplication.UnicodeUTF8))
        self.bEndFR.setText(QtGui.QApplication.translate("MainWindow", "END", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt1FR.setText(QtGui.QApplication.translate("MainWindow", "St1", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt2FR.setText(QtGui.QApplication.translate("MainWindow", "St2", None, QtGui.QApplication.UnicodeUTF8))
        self.bSt3FR.setText(QtGui.QApplication.translate("MainWindow", "St3", None, QtGui.QApplication.UnicodeUTF8))
        self.BotojumpFR.setText(QtGui.QApplication.translate("MainWindow", "Jump", None, QtGui.QApplication.UnicodeUTF8))
        self.BotomirarFR.setText(QtGui.QApplication.translate("MainWindow", "Face", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoxslowFR.setText(QtGui.QApplication.translate("MainWindow", "Very Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoslowFR.setText(QtGui.QApplication.translate("MainWindow", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.BotowalkFR.setText(QtGui.QApplication.translate("MainWindow", "Walk", None, QtGui.QApplication.UnicodeUTF8))
        self.BotorunFR.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.bHideFR.setText(QtGui.QApplication.translate("MainWindow", "Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoUpFR.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoLeftFR.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoRightFR.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.BotoDownFR.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.backspaceFR.setText(QtGui.QApplication.translate("MainWindow", "←", None, QtGui.QApplication.UnicodeUTF8))
        self.ClearFR.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "FR/LG", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFRList.setText(QtGui.QApplication.translate("MainWindow", "FR List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRubyList.setText(QtGui.QApplication.translate("MainWindow", "Ruby List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("MainWindow", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("MainWindow", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+Z", None, QtGui.QApplication.UnicodeUTF8))

