# -*- coding: utf-8 *-*

ruby_list = [["#raw 0x0 \'Mirar abajo",
              "#raw 0x1 \'Mirar arriba",
              "#raw 0x2 \'Mirar izquierda",
              "#raw 0x3 \'Mirar derecha"],

             ["#raw 0x4 \'Caminar abajo lento",
              "#raw 0x5 \'Caminar arriba lento",
              "#raw 0x6 \'Caminar izquierda lento",
              "#raw 0x7 \'Caminar derecha lento"],

             ["#raw 0x8 \'Caminar abajo velocidad normal",
              "#raw 0x9 \'Caminar arriba velocidad normal",
              "#raw 0xA \'Caminar izquierda velocidad normal",
              "#raw 0xB \'Caminar derecha velocidad normal"],

             ["#raw 0xC \'HopTileDown",
              "#raw 0xD \'HopTileUp",
              "#raw 0xE \'HopTileLeft",
              "#raw 0xF \'HopTileRight"],

             ["#raw 0x10 \'Delay0",
              "#raw 0x11 \'Delay1",
              "#raw 0x12 \'Delay2",
              "#raw 0x13 \'Delay3",
              "#raw 0x14 \'Delay4"],

             ["#raw 0x15 \'Down3",
              "#raw 0x16 \'Up3",
              "#raw 0x17 \'Left3",
              "#raw 0x18 \'Right3"],

             ["#raw 0x19 \'Step on the Spot Down (Slow)",
              "#raw 0x1A \'Step on the Spot Up (Slow)",
              "#raw 0x1B \'Step on the Spot Left (Slow)",
              "#raw 0x1C \'Step on the Spot Right (Slow)"],

             ["#raw 0x1D \'Step on the Spot Down (Normal)",
              "#raw 0x1E \'Step on the Spot Up (Normal)",
              "#raw 0x1F \'Step on the Spot Left (Normal)",
              "#raw 0x20 \'Step on the Spot Right (Normal)"],

             ["#raw 0x21 \'Step on the Spot Down (Fast)",
              "#raw 0x22 \'Step on the Spot Up (Fast)",
              "#raw 0x23 \'Step on the Spot Left (Fast)",
              "#raw 0x24 \'Step on the Spot Right (Fast)"],

             ["#raw 0x25 \'Step on the Spot Down (Very Fast)",
              "#raw 0x26 \'Step on the Spot Up (Very Fast)",
              "#raw 0x27 \'Step on the Spot Left (Very Fast)",
              "#raw 0x28 \'Step on the Spot Right (Very Fast)"],

             ["#raw 0x29 \'Down3",
              "#raw 0x2A \'Up3",
              "#raw 0x2B \'Left3",
              "#raw 0x2C \'Right3"],

             ["#raw 0x2D \'Down4",
              "#raw 0x2E \'Up4",
              "#raw 0x2F \'Left4",
              "#raw 0x30 \'Right4"],

             ["#raw 0x31 \'SlideFaceDown",
              "#raw 0x32 \'SlideFaceUp",
              "#raw 0x33 \'SlideFaceLeft",
              "#raw 0x34 \'SlideFaceRight"],

             ["#raw 0x35 \'RunDown",
              "#raw 0x36 \'RunUp",
              "#raw 0x37 \'RunLeft",
              "#raw 0x38 \'RunRight"],

             ["#raw 0x39 \'St0"],

             ["#raw 0x3A \'HighHopDown",
              "#raw 0x3B \'HighHopUp",
              "#raw 0x3C \'HighHopLeft",
              "#raw 0x3D \'HighHopRight"],

             ["#raw 0x3E \'Up0A",
              "#raw 0x3F \'Down0A",
              "#raw 0x40 \'mov40",
              "#raw 0x41 \'mov41"],

             ["#raw 0x42 \'JumpDown",
              "#raw 0x43 \'JumpUp",
              "#raw 0x44 \'JumpLeft",
              "#raw 0x45 \'JumpRight"],

             ["#raw 0x46 \'HopDown",
              "#raw 0x47 \'HopUp",
              "#raw 0x48 \'HopLeft",
              "#raw 0x49 \'HopRight"],

             ["#raw 0x4A \'HopDown180",
              "#raw 0x4B \'HopUp180",
              "#raw 0x4C \'HopLeft180",
              "#raw 0x4D \'HopRight180"],

             ["#raw 0x4F \'StRun"],

             ["#raw 0x50 \'mov50",
              "#raw 0x51 \'mov51",
              "#raw 0x52 \'mov52",
              "#raw 0x53 \'mov53"],

             ["#raw 0x54 \'Desaparecer mini",
              "#raw 0x55 \'Aparecer mini desaparecido"],

             ["#raw 0x56 \'signo !",
              "#raw 0x57 \'signo ?",
              "#raw 0x58 \'signo <3"],

             ["#raw 0x59 \'mov59",
              "#raw 0x5A \'Pokeball",
              "#raw 0x5B \'mov5B",
              "#raw 0x5C \'mov5C",
              "#raw 0x5D \'mov5D",
              "#raw 0x5E \'mov5E",
              "#raw 0x5F \'mov5F",
              "#raw 0x60 \'mov60",
              "#raw 0x61 \'mov61",
              "#raw 0x62 \'mov62",
              "#raw 0x63 \'Up0B",
              "#raw 0x64 \'mov64",
              "#raw 0x65 \'Right0A",
              "#raw 0x66 \'RunStopLoopDown",
              "#raw 0x67 \'RunStopLoopUp",
              "#raw 0x68 \'RunStopLoopLeft",
              "#raw 0x69 \'RunStopLoopRight",
              "#raw 0x6A \'StDown1i",
              "#raw 0x6B \'StUp1i",
              "#raw 0x6C \'StLeft1i",
              "#raw 0x6D \'StRight1i",
              "#raw 0x6F \'StUp5",
              "#raw 0x70 \'StLeft5",
              "#raw 0x71 \'StRight5",
              "#raw 0x72 \'Down15",
              "#raw 0x73 \'Up15",
              "#raw 0x74 \'Left15",
              "#raw 0x75 \'Right15",
              "#raw 0x76 \'mov76",
              "#raw 0x77 \'mov77",
              "#raw 0x78 \'mov78",
              "#raw 0x79 \'mov79",
              "#raw 0x7A \'Down6",
              "#raw 0x7B \'Up6",
              "#raw 0x7C \'Left6",
              "#raw 0x7D \'Right6",
              "#raw 0x7E \'RunDown2",
              "#raw 0x7F \'RunUp2",
              "#raw 0x80 \'RunLeft2",
              "#raw 0x81 \'RunRight2",
              "#raw 0x82 \'Down7",
              "#raw 0x83 \'Up7",
              "#raw 0x84 \'Left7",
              "#raw 0x85 \'Right7",
              "#raw 0x86 \'IceSlideDown",
              "#raw 0x87 \'IceSlideUp",
              "#raw 0x88 \'IceSlideLeft",
              "#raw 0x89 \'IceSlideRight"]]

