# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 418)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("applymovement-generator2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textRuby = QtWidgets.QTextBrowser(self.centralwidget)
        self.textRuby.setObjectName("textRuby")
        self.verticalLayout_2.addWidget(self.textRuby)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bAlertRuby = QtWidgets.QPushButton(self.centralwidget)
        self.bAlertRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bAlertRuby.setObjectName("bAlertRuby")
        self.horizontalLayout_3.addWidget(self.bAlertRuby)
        self.bQRuby = QtWidgets.QPushButton(self.centralwidget)
        self.bQRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bQRuby.setObjectName("bQRuby")
        self.horizontalLayout_3.addWidget(self.bQRuby)
        self.bLoveRuby = QtWidgets.QPushButton(self.centralwidget)
        self.bLoveRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bLoveRuby.setObjectName("bLoveRuby")
        self.horizontalLayout_3.addWidget(self.bLoveRuby)
        self.bEndRuby = QtWidgets.QPushButton(self.centralwidget)
        self.bEndRuby.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bEndRuby.setObjectName("bEndRuby")
        self.horizontalLayout_3.addWidget(self.bEndRuby)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Botomirar = QtWidgets.QRadioButton(self.centralwidget)
        self.Botomirar.setChecked(True)
        self.Botomirar.setObjectName("Botomirar")
        self.gridLayout_2.addWidget(self.Botomirar, 0, 0, 1, 1)
        self.Botoslow = QtWidgets.QRadioButton(self.centralwidget)
        self.Botoslow.setObjectName("Botoslow")
        self.gridLayout_2.addWidget(self.Botoslow, 1, 0, 1, 1)
        self.Botowalk = QtWidgets.QRadioButton(self.centralwidget)
        self.Botowalk.setObjectName("Botowalk")
        self.gridLayout_2.addWidget(self.Botowalk, 2, 0, 1, 1)
        self.Botorun = QtWidgets.QRadioButton(self.centralwidget)
        self.Botorun.setObjectName("Botorun")
        self.gridLayout_2.addWidget(self.Botorun, 3, 0, 1, 1)
        self.Botojump = QtWidgets.QRadioButton(self.centralwidget)
        self.Botojump.setObjectName("Botojump")
        self.gridLayout_2.addWidget(self.Botojump, 4, 0, 1, 1)
        self.bSt1Ruby = QtWidgets.QRadioButton(self.centralwidget)
        self.bSt1Ruby.setObjectName("bSt1Ruby")
        self.gridLayout_2.addWidget(self.bSt1Ruby, 0, 1, 1, 1)
        self.bSt3Ruby = QtWidgets.QRadioButton(self.centralwidget)
        self.bSt3Ruby.setObjectName("bSt3Ruby")
        self.gridLayout_2.addWidget(self.bSt3Ruby, 2, 1, 1, 1)
        self.bSt4Ruby = QtWidgets.QRadioButton(self.centralwidget)
        self.bSt4Ruby.setObjectName("bSt4Ruby")
        self.gridLayout_2.addWidget(self.bSt4Ruby, 3, 1, 1, 1)
        self.bSt2Ruby = QtWidgets.QRadioButton(self.centralwidget)
        self.bSt2Ruby.setObjectName("bSt2Ruby")
        self.gridLayout_2.addWidget(self.bSt2Ruby, 1, 1, 1, 1)
        self.bHideRuby = QtWidgets.QCheckBox(self.centralwidget)
        self.bHideRuby.setObjectName("bHideRuby")
        self.gridLayout_2.addWidget(self.bHideRuby, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.BotoUp = QtWidgets.QPushButton(self.centralwidget)
        self.BotoUp.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoUp.setObjectName("BotoUp")
        self.gridLayout.addWidget(self.BotoUp, 0, 1, 1, 1)
        self.BotoLeft = QtWidgets.QPushButton(self.centralwidget)
        self.BotoLeft.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoLeft.setObjectName("BotoLeft")
        self.gridLayout.addWidget(self.BotoLeft, 1, 0, 1, 1)
        self.BotoRight = QtWidgets.QPushButton(self.centralwidget)
        self.BotoRight.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoRight.setObjectName("BotoRight")
        self.gridLayout.addWidget(self.BotoRight, 1, 2, 1, 1)
        self.BotoDown = QtWidgets.QPushButton(self.centralwidget)
        self.BotoDown.setMaximumSize(QtCore.QSize(52, 16777215))
        self.BotoDown.setObjectName("BotoDown")
        self.gridLayout.addWidget(self.BotoDown, 2, 1, 1, 1)
        self.ClearRuby = QtWidgets.QPushButton(self.centralwidget)
        self.ClearRuby.setMaximumSize(QtCore.QSize(52, 16777215))
        self.ClearRuby.setObjectName("ClearRuby")
        self.gridLayout.addWidget(self.ClearRuby, 1, 1, 1, 1)
        self.backspaceRuby = QtWidgets.QPushButton(self.centralwidget)
        self.backspaceRuby.setMaximumSize(QtCore.QSize(52, 16777215))
        self.backspaceRuby.setObjectName("backspaceRuby")
        self.gridLayout.addWidget(self.backspaceRuby, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 516, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFRList = QtWidgets.QAction(MainWindow)
        self.actionFRList.setObjectName("actionFRList")
        self.actionRubyList = QtWidgets.QAction(MainWindow)
        self.actionRubyList.setObjectName("actionRubyList")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionRubyList)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "applymovement-gen"))
        self.textRuby.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans\'; font-size:10pt;\"><br /></p></body></html>"))
        self.bAlertRuby.setText(_translate("MainWindow", "!"))
        self.bQRuby.setText(_translate("MainWindow", "?"))
        self.bLoveRuby.setText(_translate("MainWindow", "<3"))
        self.bEndRuby.setText(_translate("MainWindow", "END"))
        self.Botomirar.setText(_translate("MainWindow", "Face"))
        self.Botoslow.setText(_translate("MainWindow", "Slow"))
        self.Botowalk.setText(_translate("MainWindow", "Walk"))
        self.Botorun.setText(_translate("MainWindow", "Run"))
        self.Botojump.setText(_translate("MainWindow", "Jump"))
        self.bSt1Ruby.setText(_translate("MainWindow", "St1"))
        self.bSt3Ruby.setText(_translate("MainWindow", "St3"))
        self.bSt4Ruby.setText(_translate("MainWindow", "St4"))
        self.bSt2Ruby.setText(_translate("MainWindow", "St2"))
        self.bHideRuby.setText(_translate("MainWindow", "Hide"))
        self.BotoUp.setText(_translate("MainWindow", "Up"))
        self.BotoLeft.setText(_translate("MainWindow", "Left"))
        self.BotoRight.setText(_translate("MainWindow", "Right"))
        self.BotoDown.setText(_translate("MainWindow", "Down"))
        self.ClearRuby.setText(_translate("MainWindow", "Clear"))
        self.backspaceRuby.setText(_translate("MainWindow", "←"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionFRList.setText(_translate("MainWindow", "FR List"))
        self.actionRubyList.setText(_translate("MainWindow", "Text List"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
